### ISSUE TITLE
Error al instalar Toponyms from Chile en Odoo 12

### ISSUE THREAD

**Issue by svenms** [OCA/l10n-chile#10]
Error al instalar el módulo en Odoo 12

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3871, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3785, in _load_records_create
    return self.create(values)
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3566, in create
    records = self._create(data_list)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3666, in _create
    cr.execute(query, params)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "res_country_state_name_code_uniq"
DETAIL:  Key (country_id, code)=(46, CL01100) already exists.

¿Qué puede ser ?

Saludo y gracias de antemano.

**Comment by nelsonramirezs** [comment]
Hola @svenms, parece que ya instalaste algún módulo con la misma data.
